name: MLOps Model Pipeline

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install mlflow numpy dvc

      - name: Handle DVC (Mock)
        run: |
          dvc init --no-scm
          dvc pull || echo "No remote data found, proceeding with local mock data."

      - name: Train and Log
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Use your DagsHub username here
          export DAGSHUB_USERNAME="RofidaRamadan" 
          python train.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: |
            mlruns/
            model_info.txt
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          name: mlflow-results
          path: . # Downloads files directly to the root folder

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install mlflow

      - name: Check Threshold
        run: python check_threshold.py

      - name: Build Docker Image
        if: success()
        run: |
          RUN_ID=$(cat model_info.txt)
          docker build --build-arg RUN_ID=$RUN_ID -t my-ml-model:latest .
